lakekeeper:
  catalog:
    image:
      tag: v0.9.1
    extraEnvFrom:
      - secretRef:
          name: lakekeeper-custom-secrets #overwrite the external database credentials with our own settings
    ingress:
      enabled: true
      host: lakekeeper.exoscale.playground.dataminded.cloud
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
        traefik.ingress.kubernetes.io/router.tls: "true"
  postgresql:
    enabled: false

  externalDatabase:
    type: postgresql
    host_read: # used from lakekeeper-custom-secrets
    port: # used from lakekeeper-custom-secrets
    user: # used from lakekeeper-custom-secrets
    database: # used from lakekeeper-custom-secrets

