# Custom values for the OPA Helm chart
# Refer to the official OPA Helm chart documentation for available options.
opa-kube-mgmt:
  opa:
    args:
      - run
      - --server
      - --addr=0.0.0.0:8181
      - --log-level=debug
      - --log-format=json
      - --set=decision_logs.console=true
      - /var/lib/opa/policies
  useHttps: false

  image:
    repository: openpolicyagent/opa
    tag: "1.3.0" # Specify the OPA version you want to use
    pullPolicy: Always

  extraEnv:
    - name: LAKEKEEPER_URL
      valueFrom:
        secretKeyRef:
          name: opa-secrets
          key: LAKEKEEPER_URL
    - name: LAKEKEEPER_TOKEN_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: opa-secrets
          key: LAKEKEEPER_TOKEN_ENDPOINT
    - name: LAKEKEEPER_SCOPE
      valueFrom:
        secretKeyRef:
          name: opa-secrets
          key: LAKEKEEPER_SCOPE
    - name: TRINO_LAKEKEEPER_CATALOG_NAME
      valueFrom:
        secretKeyRef:
          name: opa-secrets
          key: TRINO_LAKEKEEPER_CATALOG_NAME
    - name: LAKEKEEPER_LAKEKEEPER_WAREHOUSE
      valueFrom:
        secretKeyRef:
          name: opa-secrets
          key: LAKEKEEPER_LAKEKEEPER_WAREHOUSE
    - name: LAKEKEEPER_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: opa-credentials
          key: CLIENT_ID
    - name: LAKEKEEPER_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: opa-credentials
          key: CLIENT_SECRET

  authz:
  # Disable if you don't want authorization.
  # Mostly useful for debugging.
    enabled: false

  mgmt:
    enabled: false

